[build]
  base = "sveltekit"
  command = "rm -rf node_modules package-lock.json && pnpm run install && pnpm run build"
  publish = "build"

[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"